<?php

/*
 * Auto generated by polyfony-inc/console 
 * on __datetime__
 *
 */

// framework aliases
use Polyfony\Controller as Controller;
use Polyfony\Exception as Exception;
use Polyfony\Security as Security;
use Polyfony\Response as Response;
use Polyfony\Request as Request;
use Polyfony\Router as Router;
use Polyfony\Config as Config;
use Polyfony\Keys as Keys;

use Polyfony\Form\Token as Token;
use Polyfony\Form\Captcha as Captcha;

// models aliases
use Models\__Table__ as __Table__;

// vendors aliases
use Bootstrap\Alert\Success as OK;
use Bootstrap\Alert\Failure as KO;
use Bootstrap\Alert as Alert;

class __Table__Controller extends Controller {

	 //  _          __             
	 // | |__  ___ / _|___ _ _ ___ 
	 // | '_ \/ -_)  _/ _ \ '_/ -_)
	 // |_.__/\___|_| \___/_| \___|                            

	public function preAction() {

		// Enforce a global security
		// Security::enforce('control-__table__', 1);

		Response\HTML::set([
			'metas'		=>[
				'title'	=>'__Bundle__ - __Table__'
			],
			'links'		=>[
				'//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css',
				'//use.fontawesome.com/releases/v5.3.1/css/all.css'
			],
			'scripts'	=>[
				'//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'
			]
		]);

		// ...

	}



	 //  _         _         
	 // (_)_ _  __| |_____ __
	 // | | ' \/ _` / -_) \ /
	 // |_|_||_\__,_\___/_\_\
                      
	public function indexAction() {

		// request has been posted
		$this->__Table__ = Request::isPost() ? 
			__Table__::search(
				array_filter(
					Request::post('__Table__')
				)
			) : [];
		
		// the list view
		$this->view('__Table__/Index');

	}

	 //         _ _ _   
	 //  ___ __| (_) |_ 
	 // / -_) _` | |  _|
	 // \___\__,_|_|\__|
                 
	public function editAction() {

		// enforce security
		// Security::enforce('edit-__table__', 1);

		// get that __Singular__
		$this->__Singular__ = new __Table__(Request::get('id'));

		// request has been posted
		if(Request::isPost()) {
			
			// enforce security
			// Security::enforce('edit-post-__table__', 1);

			// enforce the CSRF protection
			Token::enforce();

			// record has been updated/saved ?
			$this
				->__Singular__
				->set(Request::post('__Table__'))
				->save() ? 
					(new OK) : 
					(new KO);

			// redirect to the previous page
			Response::previous();

		}

		$this->view('__Table__/Edit');

	}

	 //     _     _     _       
	 //  __| |___| |___| |_ ___ 
	 // / _` / -_) / -_)  _/ -_)
	 // \__,_\___|_\___|\__\___|
                         
	public function deleteAction() {

		// enforce security
		// Security::enforce('delete-__table__', 1);

		// get that __Singular__
		$this->__Singular__ = new __Table__(Request::get('id'));

		// request has been posted
		if(Request::isPost()) {
			
			// enforce the CSRF protection
			Token::enforce();

			// record has been deleted ?
			$this
				->__Singular__
				->delete() ? 
					(new OK) : 
					(new KO);

			// redirect somewhere else
			Response::setRedirect(
				Router::reverse('__table__')
			);
			Response::render();

		}
		else {

			$this->view('__Table__/Delete');

		}

		
	}

	 //                  _       
	 //  __ _ _ ___ __ _| |_ ___ 
	 // / _| '_/ -_) _` |  _/ -_)
	 // \__|_| \___\__,_|\__\___|
                          
	public function createAction() {

		// enforce security
		// Security::enforce('create-__table__', 1);

		// get that __Singular__
		$this->__Singular__ = new __Table__;

		// request has been posted
		if(Request::isPost()) {
			
			// enforce the CSRF protection
			Token::enforce();

			// record has been updated/saved ?
			$this
				->__Singular__
				->set(Request::post('__Table__'))
				->save() ? 
					(new OK) : 
					(new KO);

			// redirect to the previous page
			Response::setRedirect(
				$this->__Singular__->getUrl()
			);
			Response::render();

		}

		$this->view('__Table__/Edit');

	}


	 //        __ _           
	 //  __ _ / _| |_ ___ _ _ 
	 // / _` |  _|  _/ -_) '_|
	 // \__,_|_|  \__\___|_|  
                       
	public function postAction() {
		// ...
	}

}

?>