<?php

/*
 * Auto generated by polyfony-inc/console 
 * on __datetime__
 *
 */

use Polyfony as pf;

class __Table__Controller extends Polyfony\Controller {

	 //  _          __             
	 // | |__  ___ / _|___ _ _ ___ 
	 // | '_ \/ -_)  _/ _ \ '_/ -_)
	 // |_.__/\___|_| \___/_| \___|                            

	public function preAction() {

		// Enforce a global security
		// Polyfony\Security::enforce('control-__Table__', 1);

		// Polyfony\Response::set([
		// 	'metas'		=>[
		// 		'title'			=>'',
		// 		'description'	=>'',
		//		'robots'		=>''
		// 	],
		// 	'assets'	=>[
		// 		'css'	=>[
		// 		],
		// 		'js'	=>[
		// 		]
		// 	]
		// ]);

		// ...

	}



	 //  _         _         
	 // (_)_ _  __| |_____ __
	 // | | ' \/ _` / -_) \ /
	 // |_|_||_\__,_\___/_\_\
                      
	public function indexAction() {

		// request has been posted
		if(Polyfony\Request::isPost()) {
		
			// search in the table
			$this->__Table__ = Models\__Table__::search(
				Polyfony\Request::post('__Table__')
			);

			// reusults found ?
			$this->__Table__ ? 

				// save a success alert to the flashbag
				new Bootstrap\Alert([
					'class'		=>'success',
					'message'	=>'Found {count($this->__Table__)} {$this->__Table__}'
				])->save() : 

				// save a warning alert to the flashbag
				new Bootstrap\Alert([
					'class'		=>'warning',
					'message'	=>'No {$this->__Table__} found'
				])->save();

		}
		else {
			// empty result set
			$this->__Table__ = [];
		}

		// the list view
		$this->view('__Table__/Index');

	}

	 //         _ _ _   
	 //  ___ __| (_) |_ 
	 // / -_) _` | |  _|
	 // \___\__,_|_|\__|
                 
	public function editAction() {

		// enforce security
		// Polyfony\Security::enforce('edit-__Table__', 1);

		// get that __Singular__
		$this->__Singular__ = new Models\__Table__(Polyfony\Request::post('id'));

		// request has been posted
		if(Polyfony\Request::isPost()) {
			
			// enforce security
			// Polyfony\Security::enforce('edit-post-__Table__', 1);

			// enforce the CSRF protection
			Polyfony\Form\Token::enforce();

			// record has been updated/saved ?
			$this
				->__Singular__
				->set(Polyfony\Request::post('__Table__'))
				->save() ? 

					// save a success alert to the flashbag
					new Bootstrap\Alert([
						'class'		=>'success',
						'message'	=>'The {$this->__Table__} has been saved'
					])->save() : 

					// save a warning alert to the flashbag
					new Bootstrap\Alert([
						'class'		=>'danger',
						'message'	=>'Error during the saving of the {__Table__}'
					])->save();

			// redirect to the previous page
		}

		$this->view('__Table__/Edit');

	}

	 //     _     _     _       
	 //  __| |___| |___| |_ ___ 
	 // / _` / -_) / -_)  _/ -_)
	 // \__,_\___|_\___|\__\___|
                         
	public function deleteAction() {

		// enforce security
		// Polyfony\Security::enforce('delete-__Table__', 1);

		// get that __Singular__
		$this->__Singular__ = new Models\__Table__(Polyfony\Request::post('id'));

		// request has been posted
		if(Polyfony\Request::isPost()) {
			
			// enforce the CSRF protection
			Polyfony\Form\Token::enforce();

			// record has been deleted ?
			$this
				->__Singular__
				->delete() ? 

					// save a success alert to the flashbag
					new Bootstrap\Alert([
						'class'		=>'success',
						'message'	=>'{$this->__Table__} has been deleted'
					])->save() : 

					// save a warning alert to the flashbag
					new Bootstrap\Alert([
						'class'		=>'danger',
						'message'	=>'Error while deleting {__Table__}'
					])->save();

			// redirect somewhere else

		}
		else {

			$this->view('__Table__/Delete');

		}

		
	}

	 //                  _       
	 //  __ _ _ ___ __ _| |_ ___ 
	 // / _| '_/ -_) _` |  _/ -_)
	 // \__|_| \___\__,_|\__\___|
                          
	public function createAction() {

		// enforce security
		// Polyfony\Security::enforce('create-__Table__', 1);

		$this->view('__Table__/Create');

	}


	 //        __ _           
	 //  __ _ / _| |_ ___ _ _ 
	 // / _` |  _|  _/ -_) '_|
	 // \__,_|_|  \__\___|_|  
                       
	public function postAction() {
		// ...
	}

}

?>