<?php

/*
 * Auto generated by polyfony-inc/console 
 * on __datetime__
 *
 */

namespace Controllers;

// framework aliases
use \Polyfony\{ 
	Exception, Security, Response, Request, Element,
	Router, Form, Config, Logger, Controller, Hashs, 
	Locales, Cache, Form\Captcha, Form\Token
};

// models aliases
use \Models\__Table__ as __Table__;

// vendors aliases
use \Bootstrap\{
	Alert, 
	Alert\Success as OK, 
	Alert\Failure as KO
};

// helpers
// use \Helpers\Something;


class __Table__Controller extends Controller {

	 //  _          __             
	 // | |__  ___ / _|___ _ _ ___ 
	 // | '_ \/ -_)  _/ _ \ '_/ -_)
	 // |_.__/\___|_| \___/_| \___|                            

	public function before() {

		// Enforce a global security
		// Security::authenticate();
		// Security::denyUnlessHasRole('__bundle__');
		// Security::denyUnlessHasPermission('__table__');

		Response\HTML::set([
			'metas'		=>[
				'title'	=>'__Bundle__ - __Table__'
			],
			'links'		=>Config::get('response', 'links'),
			'scripts'	=>Config::get('response', 'scripts')
		]);

		// ...

	}



	 //  _         _         
	 // (_)_ _  __| |_____ __
	 // | | ' \/ _` / -_) \ /
	 // |_|_||_\__,_\___/_\_\
                      
	public function index() {

		// the list view
		$this->view('__Table__/Index', [
			// if a request has been posted
			'__table__'=>Request::isPost() ? 
				// search the table
				__Table__::search(
					// with filtered down search parameters
					array_filter(
						Request::post('__Table__')
					)
				) : []
		]);

	}

	 //         _ _ _   
	 //  ___ __| (_) |_ 
	 // / -_) _` | |  _|
	 // \___\__,_|_|\__|
                 
	public function edit() {

		// enforce security
		// Security::denyUnlessHasPermission('edit-__table__');

		// get that __Singular__
		$__singular__ = new __Table__(Request::get('id'));

		// request has been posted
		if(Request::isPost()) {
			
			// enforce security
			// Security::denyUnlessHasPermission('edit-post-__table__');

			// enforce the CSRF protection
			Token::enforce();

			// record has been updated/saved ?
			$__singular__
				->set(Request::post('__Table__'))
				->save() ? 
					(new OK) : 
					(new KO);

			// redirect to the previous page
			Response::previous();

		}

		$this->view('__Table__/Edit', [
			'__singular__'=>$__singular
		]);

	}

	 //     _     _     _       
	 //  __| |___| |___| |_ ___ 
	 // / _` / -_) / -_)  _/ -_)
	 // \__,_\___|_\___|\__\___|
                         
	public function delete() {

		// enforce security
		// Security::denyUnlessHasPermission('delete-__table__', 1);

		// get that __Singular__
		$__singular__ = new __Table__(Request::get('id'));

		// request has been posted
		if(Request::isPost()) {
			
			// enforce the CSRF protection
			Token::enforce();

			// record has been deleted ?
			$__singular__
				->delete() ? 
					(new OK)->save() : 
					(new KO)->save();

			// redirect somewhere else
			Response::setRedirect(
				Router::reverse('__table__')
			);
			Response::render();

		}
		else {

			$this->view('__Table__/Delete', [
				'__singular__'=>$__singular__
			]);

		}

		
	}

	 //                  _       
	 //  __ _ _ ___ __ _| |_ ___ 
	 // / _| '_/ -_) _` |  _/ -_)
	 // \__|_| \___\__,_|\__\___|
                          
	public function create() {

		// enforce security
		// Security::denyUnlessHasPermission('create-__table__', 1);

		// get that __Singular__
		$__singular__ = new __Table__;

		// request has been posted
		if(Request::isPost()) {
			
			// enforce the CSRF protection
			Token::enforce();

			// record has been updated/saved ?
			$__singular__
				->set(Request::post('__Table__'))
				->save() ? 
					(new OK)->save() : 
					(new KO)->save();

			// redirect to the previous page
			Response::setRedirect(
				$__singular__->getUrl()
			);
			Response::render();

		}

		$this->view('__Table__/Edit', [
			'__singular__'=>$__singular__
		]);

	}


	 //        __ _           
	 //  __ _ / _| |_ ___ _ _ 
	 // / _` |  _|  _/ -_) '_|
	 // \__,_|_|  \__\___|_|  
                       
	public function after() {
		// ...
	}

}

?>